env:
  mocha: true
  node: true
extends: 'eslint:recommended'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-trailing-spaces:
    - error